//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GssInteropClass.CM.Gss {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gss.sintef.no/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gss.sintef.no/")]
    public partial class httpHeaderField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gss.sintef.no/")]
    public partial class requestDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private httpHeaderField[] headersField;
        
        private string httpMethodField;
        
        private string sessionTokenFieldField;
        
        private bool supportedField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("headers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public httpHeaderField[] headers {
            get {
                return this.headersField;
            }
            set {
                this.headersField = value;
                this.RaisePropertyChanged("headers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string httpMethod {
            get {
                return this.httpMethodField;
            }
            set {
                this.httpMethodField = value;
                this.RaisePropertyChanged("httpMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sessionTokenField {
            get {
                return this.sessionTokenFieldField;
            }
            set {
                this.sessionTokenFieldField = value;
                this.RaisePropertyChanged("sessionTokenField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool supported {
            get {
                return this.supportedField;
            }
            set {
                this.supportedField = value;
                this.RaisePropertyChanged("supported");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gss.sintef.no/")]
    public partial class resourceInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requestDescription createDescriptionField;
        
        private requestDescription deleteDescriptionField;
        
        private requestDescription metaReadDescriptionField;
        
        private bool queryForNameField;
        
        private requestDescription readDescriptionField;
        
        private string typeField;
        
        private string uniqueNameField;
        
        private requestDescription updateDescriptionField;
        
        private string visualNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public requestDescription createDescription {
            get {
                return this.createDescriptionField;
            }
            set {
                this.createDescriptionField = value;
                this.RaisePropertyChanged("createDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public requestDescription deleteDescription {
            get {
                return this.deleteDescriptionField;
            }
            set {
                this.deleteDescriptionField = value;
                this.RaisePropertyChanged("deleteDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public requestDescription metaReadDescription {
            get {
                return this.metaReadDescriptionField;
            }
            set {
                this.metaReadDescriptionField = value;
                this.RaisePropertyChanged("metaReadDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool queryForName {
            get {
                return this.queryForNameField;
            }
            set {
                this.queryForNameField = value;
                this.RaisePropertyChanged("queryForName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public requestDescription readDescription {
            get {
                return this.readDescriptionField;
            }
            set {
                this.readDescriptionField = value;
                this.RaisePropertyChanged("readDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string uniqueName {
            get {
                return this.uniqueNameField;
            }
            set {
                this.uniqueNameField = value;
                this.RaisePropertyChanged("uniqueName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public requestDescription updateDescription {
            get {
                return this.updateDescriptionField;
            }
            set {
                this.updateDescriptionField = value;
                this.RaisePropertyChanged("updateDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string visualName {
            get {
                return this.visualNameField;
            }
            set {
                this.visualNameField = value;
                this.RaisePropertyChanged("visualName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gss.sintef.no/", ConfigurationName="CM.Gss.FileUtilities")]
    public interface FileUtilities {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/listFilesMinimalRequest", ReplyAction="http://gss.sintef.no/FileUtilities/listFilesMinimalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GssInteropClass.CM.Gss.IOException), Action="http://gss.sintef.no/FileUtilities/listFilesMinimal/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GssInteropClass.CM.Gss.listFilesMinimalResponse listFilesMinimal(GssInteropClass.CM.Gss.listFilesMinimalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/listFilesMinimalRequest", ReplyAction="http://gss.sintef.no/FileUtilities/listFilesMinimalResponse")]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.listFilesMinimalResponse> listFilesMinimalAsync(GssInteropClass.CM.Gss.listFilesMinimalRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/createFolderRequest", ReplyAction="http://gss.sintef.no/FileUtilities/createFolderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GssInteropClass.CM.Gss.IOException), Action="http://gss.sintef.no/FileUtilities/createFolder/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GssInteropClass.CM.Gss.createFolderResponse createFolder(GssInteropClass.CM.Gss.createFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/createFolderRequest", ReplyAction="http://gss.sintef.no/FileUtilities/createFolderResponse")]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.createFolderResponse> createFolderAsync(GssInteropClass.CM.Gss.createFolderRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/deleteFolderRequest", ReplyAction="http://gss.sintef.no/FileUtilities/deleteFolderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GssInteropClass.CM.Gss.IOException), Action="http://gss.sintef.no/FileUtilities/deleteFolder/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GssInteropClass.CM.Gss.deleteFolderResponse deleteFolder(GssInteropClass.CM.Gss.deleteFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/deleteFolderRequest", ReplyAction="http://gss.sintef.no/FileUtilities/deleteFolderResponse")]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.deleteFolderResponse> deleteFolderAsync(GssInteropClass.CM.Gss.deleteFolderRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/getResourceInformationRequest", ReplyAction="http://gss.sintef.no/FileUtilities/getResourceInformationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GssInteropClass.CM.Gss.IOException), Action="http://gss.sintef.no/FileUtilities/getResourceInformation/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GssInteropClass.CM.Gss.getResourceInformationResponse getResourceInformation(GssInteropClass.CM.Gss.getResourceInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/getResourceInformationRequest", ReplyAction="http://gss.sintef.no/FileUtilities/getResourceInformationResponse")]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.getResourceInformationResponse> getResourceInformationAsync(GssInteropClass.CM.Gss.getResourceInformationRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/containsFileRequest", ReplyAction="http://gss.sintef.no/FileUtilities/containsFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GssInteropClass.CM.Gss.IOException), Action="http://gss.sintef.no/FileUtilities/containsFile/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GssInteropClass.CM.Gss.containsFileResponse containsFile(GssInteropClass.CM.Gss.containsFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/containsFileRequest", ReplyAction="http://gss.sintef.no/FileUtilities/containsFileResponse")]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.containsFileResponse> containsFileAsync(GssInteropClass.CM.Gss.containsFileRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/listFilesRequest", ReplyAction="http://gss.sintef.no/FileUtilities/listFilesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GssInteropClass.CM.Gss.IOException), Action="http://gss.sintef.no/FileUtilities/listFiles/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GssInteropClass.CM.Gss.listFilesResponse listFiles(GssInteropClass.CM.Gss.listFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gss.sintef.no/FileUtilities/listFilesRequest", ReplyAction="http://gss.sintef.no/FileUtilities/listFilesResponse")]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.listFilesResponse> listFilesAsync(GssInteropClass.CM.Gss.listFilesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listFilesMinimal", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class listFilesMinimalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        public string fileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=1)]
        public string session_id;
        
        public listFilesMinimalRequest() {
        }
        
        public listFilesMinimalRequest(string fileID, string session_id) {
            this.fileID = fileID;
            this.session_id = session_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listFilesMinimalResponse", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class listFilesMinimalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GssInteropClass.CM.Gss.resourceInformation[] @return;
        
        public listFilesMinimalResponse() {
        }
        
        public listFilesMinimalResponse(GssInteropClass.CM.Gss.resourceInformation[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFolder", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class createFolderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        public string folderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=1)]
        public string session_id;
        
        public createFolderRequest() {
        }
        
        public createFolderRequest(string folderID, string session_id) {
            this.folderID = folderID;
            this.session_id = session_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFolderResponse", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class createFolderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GssInteropClass.CM.Gss.resourceInformation @return;
        
        public createFolderResponse() {
        }
        
        public createFolderResponse(GssInteropClass.CM.Gss.resourceInformation @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFolder", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class deleteFolderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        public string folderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=1)]
        public string session_id;
        
        public deleteFolderRequest() {
        }
        
        public deleteFolderRequest(string folderID, string session_id) {
            this.folderID = folderID;
            this.session_id = session_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFolderResponse", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class deleteFolderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteFolderResponse() {
        }
        
        public deleteFolderResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResourceInformation", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class getResourceInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        public string fileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=1)]
        public string session_id;
        
        public getResourceInformationRequest() {
        }
        
        public getResourceInformationRequest(string fileID, string session_id) {
            this.fileID = fileID;
            this.session_id = session_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResourceInformationResponse", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class getResourceInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GssInteropClass.CM.Gss.resourceInformation @return;
        
        public getResourceInformationResponse() {
        }
        
        public getResourceInformationResponse(GssInteropClass.CM.Gss.resourceInformation @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="containsFile", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class containsFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        public string fileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=1)]
        public string session_id;
        
        public containsFileRequest() {
        }
        
        public containsFileRequest(string fileID, string session_id) {
            this.fileID = fileID;
            this.session_id = session_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="containsFileResponse", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class containsFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public containsFileResponse() {
        }
        
        public containsFileResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listFiles", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class listFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        public string fileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=1)]
        public string session_id;
        
        public listFilesRequest() {
        }
        
        public listFilesRequest(string fileID, string session_id) {
            this.fileID = fileID;
            this.session_id = session_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listFilesResponse", WrapperNamespace="http://gss.sintef.no/", IsWrapped=true)]
    public partial class listFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gss.sintef.no/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GssInteropClass.CM.Gss.resourceInformation[] @return;
        
        public listFilesResponse() {
        }
        
        public listFilesResponse(GssInteropClass.CM.Gss.resourceInformation[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileUtilitiesChannel : GssInteropClass.CM.Gss.FileUtilities, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileUtilitiesClient : System.ServiceModel.ClientBase<GssInteropClass.CM.Gss.FileUtilities>, GssInteropClass.CM.Gss.FileUtilities {
        
        public FileUtilitiesClient() {
        }
        
        public FileUtilitiesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileUtilitiesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileUtilitiesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileUtilitiesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GssInteropClass.CM.Gss.listFilesMinimalResponse GssInteropClass.CM.Gss.FileUtilities.listFilesMinimal(GssInteropClass.CM.Gss.listFilesMinimalRequest request) {
            return base.Channel.listFilesMinimal(request);
        }
        
        public GssInteropClass.CM.Gss.resourceInformation[] listFilesMinimal(string fileID, string session_id) {
            GssInteropClass.CM.Gss.listFilesMinimalRequest inValue = new GssInteropClass.CM.Gss.listFilesMinimalRequest();
            inValue.fileID = fileID;
            inValue.session_id = session_id;
            GssInteropClass.CM.Gss.listFilesMinimalResponse retVal = ((GssInteropClass.CM.Gss.FileUtilities)(this)).listFilesMinimal(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.listFilesMinimalResponse> GssInteropClass.CM.Gss.FileUtilities.listFilesMinimalAsync(GssInteropClass.CM.Gss.listFilesMinimalRequest request) {
            return base.Channel.listFilesMinimalAsync(request);
        }
        
        public System.Threading.Tasks.Task<GssInteropClass.CM.Gss.listFilesMinimalResponse> listFilesMinimalAsync(string fileID, string session_id) {
            GssInteropClass.CM.Gss.listFilesMinimalRequest inValue = new GssInteropClass.CM.Gss.listFilesMinimalRequest();
            inValue.fileID = fileID;
            inValue.session_id = session_id;
            return ((GssInteropClass.CM.Gss.FileUtilities)(this)).listFilesMinimalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GssInteropClass.CM.Gss.createFolderResponse GssInteropClass.CM.Gss.FileUtilities.createFolder(GssInteropClass.CM.Gss.createFolderRequest request) {
            return base.Channel.createFolder(request);
        }
        
        public GssInteropClass.CM.Gss.resourceInformation createFolder(string folderID, string session_id) {
            GssInteropClass.CM.Gss.createFolderRequest inValue = new GssInteropClass.CM.Gss.createFolderRequest();
            inValue.folderID = folderID;
            inValue.session_id = session_id;
            GssInteropClass.CM.Gss.createFolderResponse retVal = ((GssInteropClass.CM.Gss.FileUtilities)(this)).createFolder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.createFolderResponse> GssInteropClass.CM.Gss.FileUtilities.createFolderAsync(GssInteropClass.CM.Gss.createFolderRequest request) {
            return base.Channel.createFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<GssInteropClass.CM.Gss.createFolderResponse> createFolderAsync(string folderID, string session_id) {
            GssInteropClass.CM.Gss.createFolderRequest inValue = new GssInteropClass.CM.Gss.createFolderRequest();
            inValue.folderID = folderID;
            inValue.session_id = session_id;
            return ((GssInteropClass.CM.Gss.FileUtilities)(this)).createFolderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GssInteropClass.CM.Gss.deleteFolderResponse GssInteropClass.CM.Gss.FileUtilities.deleteFolder(GssInteropClass.CM.Gss.deleteFolderRequest request) {
            return base.Channel.deleteFolder(request);
        }
        
        public bool deleteFolder(string folderID, string session_id) {
            GssInteropClass.CM.Gss.deleteFolderRequest inValue = new GssInteropClass.CM.Gss.deleteFolderRequest();
            inValue.folderID = folderID;
            inValue.session_id = session_id;
            GssInteropClass.CM.Gss.deleteFolderResponse retVal = ((GssInteropClass.CM.Gss.FileUtilities)(this)).deleteFolder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.deleteFolderResponse> GssInteropClass.CM.Gss.FileUtilities.deleteFolderAsync(GssInteropClass.CM.Gss.deleteFolderRequest request) {
            return base.Channel.deleteFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<GssInteropClass.CM.Gss.deleteFolderResponse> deleteFolderAsync(string folderID, string session_id) {
            GssInteropClass.CM.Gss.deleteFolderRequest inValue = new GssInteropClass.CM.Gss.deleteFolderRequest();
            inValue.folderID = folderID;
            inValue.session_id = session_id;
            return ((GssInteropClass.CM.Gss.FileUtilities)(this)).deleteFolderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GssInteropClass.CM.Gss.getResourceInformationResponse GssInteropClass.CM.Gss.FileUtilities.getResourceInformation(GssInteropClass.CM.Gss.getResourceInformationRequest request) {
            return base.Channel.getResourceInformation(request);
        }
        
        public GssInteropClass.CM.Gss.resourceInformation getResourceInformation(string fileID, string session_id) {
            GssInteropClass.CM.Gss.getResourceInformationRequest inValue = new GssInteropClass.CM.Gss.getResourceInformationRequest();
            inValue.fileID = fileID;
            inValue.session_id = session_id;
            GssInteropClass.CM.Gss.getResourceInformationResponse retVal = ((GssInteropClass.CM.Gss.FileUtilities)(this)).getResourceInformation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.getResourceInformationResponse> GssInteropClass.CM.Gss.FileUtilities.getResourceInformationAsync(GssInteropClass.CM.Gss.getResourceInformationRequest request) {
            return base.Channel.getResourceInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GssInteropClass.CM.Gss.getResourceInformationResponse> getResourceInformationAsync(string fileID, string session_id) {
            GssInteropClass.CM.Gss.getResourceInformationRequest inValue = new GssInteropClass.CM.Gss.getResourceInformationRequest();
            inValue.fileID = fileID;
            inValue.session_id = session_id;
            return ((GssInteropClass.CM.Gss.FileUtilities)(this)).getResourceInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GssInteropClass.CM.Gss.containsFileResponse GssInteropClass.CM.Gss.FileUtilities.containsFile(GssInteropClass.CM.Gss.containsFileRequest request) {
            return base.Channel.containsFile(request);
        }
        
        public bool containsFile(string fileID, string session_id) {
            GssInteropClass.CM.Gss.containsFileRequest inValue = new GssInteropClass.CM.Gss.containsFileRequest();
            inValue.fileID = fileID;
            inValue.session_id = session_id;
            GssInteropClass.CM.Gss.containsFileResponse retVal = ((GssInteropClass.CM.Gss.FileUtilities)(this)).containsFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.containsFileResponse> GssInteropClass.CM.Gss.FileUtilities.containsFileAsync(GssInteropClass.CM.Gss.containsFileRequest request) {
            return base.Channel.containsFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<GssInteropClass.CM.Gss.containsFileResponse> containsFileAsync(string fileID, string session_id) {
            GssInteropClass.CM.Gss.containsFileRequest inValue = new GssInteropClass.CM.Gss.containsFileRequest();
            inValue.fileID = fileID;
            inValue.session_id = session_id;
            return ((GssInteropClass.CM.Gss.FileUtilities)(this)).containsFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GssInteropClass.CM.Gss.listFilesResponse GssInteropClass.CM.Gss.FileUtilities.listFiles(GssInteropClass.CM.Gss.listFilesRequest request) {
            return base.Channel.listFiles(request);
        }
        
        public GssInteropClass.CM.Gss.resourceInformation[] listFiles(string fileID, string session_id) {
            GssInteropClass.CM.Gss.listFilesRequest inValue = new GssInteropClass.CM.Gss.listFilesRequest();
            inValue.fileID = fileID;
            inValue.session_id = session_id;
            GssInteropClass.CM.Gss.listFilesResponse retVal = ((GssInteropClass.CM.Gss.FileUtilities)(this)).listFiles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GssInteropClass.CM.Gss.listFilesResponse> GssInteropClass.CM.Gss.FileUtilities.listFilesAsync(GssInteropClass.CM.Gss.listFilesRequest request) {
            return base.Channel.listFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GssInteropClass.CM.Gss.listFilesResponse> listFilesAsync(string fileID, string session_id) {
            GssInteropClass.CM.Gss.listFilesRequest inValue = new GssInteropClass.CM.Gss.listFilesRequest();
            inValue.fileID = fileID;
            inValue.session_id = session_id;
            return ((GssInteropClass.CM.Gss.FileUtilities)(this)).listFilesAsync(inValue);
        }
    }
}
